### ISSUE TITLE
edge vs edges

### ISSUE THREAD

**Issue by bergel** [cjrohrbach/BA-GT-Roassal#25]
Consider the following example:

```Smalltalk
v := CRMondrian new.
v nodes circle with: (1 to: 100).
v edge connectFrom: [ :nb | nb // 2].
v
```

We have `nodes` to define the nodes, and we have `edge` to define edges. Shouldn't it be `edges` instead?

**Comment by cjrohrbach** [comment]
Sure would make more sense
